version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "docker_db"
      MYSQL_USER: "audran"
      MYSQL_PASSWORD: "40da40cg"
      MYSQL_ALLOW_EMPTY_PASSWORD: 
      MYSQL_RANDOM_ROOT_PASSWORD: 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080